---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: none
BASH_FILTER_REGEX_INCLUDE: (scripts/*)
BASH_SHFMT_FILE_EXTENSIONS: "*"
DISABLE:
  - CLOUDFORMATION
  - COPYPASTE
  - CSS
  - TEKTON
  - MARKDOWN
  - HTML
  - REPOSITORY
DISABLE_LINTERS:
  - BASH_SHELLCHECK
  - SPELL_CSPELL
  - JSON_PRETTIER
  - JSON_V8R
  - REPOSITORY_GITLEAKS
  - SPELL_PROSELINT
  - DOCKERFILE_HADOLINT
  - YAML_PRETTIER
  - YAML_V8R
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - TERRAFORM_TFLINT
  - TERRAFORM_CHECKOV
  - TERRAFORM_TERRASCAN
  - TERRAFORM_KICS
  - REPOSITORY_GITLEAKS
  - PYTHON_ISORT
  - PYTHON_MYPY
  - PYTHON_BANDIT
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - PYTHON_FLAKE8
  - PYTHON_BLACK
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_ES_FILTER_REGEX_EXCLUDE: src/django/web/templates/web/environment.js
JAVASCRIPT_ES_RULES_PATH: src/app/
JAVASCRIPT_ES_FILE_EXTENSIONS:
  - .js
  - .jsx
  - .ts
  - .tsx
JAVASCRIPT_PRETTIER_DISABLE_ERRORS: false
JAVASCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .js
  - .jsx
  - .ts
  - .tsx
JAVASCRIPT_PRETTIER_FILTER_REGEX_INCLUDE: src/app/
JAVASCRIPT_PRETTIER_RULES_PATH: src/app/
TYPESCRIPT_PRETTIER_RULES_PATH: src/app/
UPDATED_SOURCES_REPORTER: false
SHOW_ELAPSED_TIME: true
