---

services:
  app:
    image: node:18-slim
    stdin_open: true
    working_dir: /usr/local/src
    environment:
      - REACT_APP_GIT_COMMIT=${REACT_APP_GIT_COMMIT:-latest}
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - PORT=8765
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./src/app:/usr/local/src
      - node-modules-volume:/usr/local/src/node_modules
    command: yarn start

volumes:
  node-modules-volume:
