---

services:
  app:
    image: node:18-slim
    stdin_open: true
    working_dir: /usr/local/src
    environment:
      - REACT_APP_GIT_COMMIT=${REACT_APP_GIT_COMMIT:-latest}
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - PORT=4567
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./src/app:/usr/local/src
      - ./src/django/static:/usr/local/src/build
      - node-modules-volume:/usr/local/src/node_modules
    command: yarn start

  database:
    image: postgis/postgis:13-3.1
    environment:
      - POSTGRES_USER=$PROJECTNAME
      - POSTGRES_PASSWORD=$PROJECTNAME
      - POSTGRES_DB=$PROJECTNAME
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$PROJECTNAME", '-h', 'database']
      interval: 1s
      timeout: 30s
      retries: 30

  django:
    image: "$PROJECTNAME-django:${GIT_COMMIT:-default}"
    env_file: .env
    environment:
      - PGHOST=database
      - PGPORT=5432
      - PGUSER=$PROJECTNAME
      - PGPASSWORD=$PROJECTNAME
      - PGDATABASE=$PROJECTNAME
      - DJANGO_ENV=Development
      - DJANGO_SECRET_KEY=secret
      - DJANGO_LOG_LEVEL=INFO
      - DJANGO_ALLOWED_HOSTS=localhost,django
    build:
      context: ./src/django
      dockerfile: Dockerfile
      labels:
        com.project.name: "project-name"
    volumes:
      - ./src/django:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
    working_dir: /usr/local/src
    depends_on:
      database:
        condition: service_healthy

volumes:
  node-modules-volume:
