#!/bin/bash

USAGE="Run tasks before building images in CI"

source ./scripts/_sourced
check_for_help_flag "$@"

echo "Setting version.json"
BUILD_DATE=$(date)
VERSION_DATA='{"buildDate":"'${BUILD_DATE}'","gitSHA":"'${GIT_COMMIT}'"}'

VERSION_FILE=src/django/version.json
if [[ -f "$VERSION_FILE" ]]; then
    echo "Removing old version file"
    rm $VERSION_FILE
fi
touch $VERSION_FILE
echo "$VERSION_DATA" >$VERSION_FILE
