#!/bin/bash

USAGE="Lint the project's code with optional format

Options:
format - run formatting too.
staged - lint staged files only (with formatting)."

source ./scripts/_sourced
check_for_help_flag "$@"

MEGALINTER_FILES_TO_LINT=
if [[ "${1:-}" == "format" ]]; then
    echo "Formatting"
    APPLY_FIXES=all
elif [[ "${1:-}" == "staged" ]]; then
    echo "Formatting staged files only"
    APPLY_FIXES=all
    MEGALINTER_FILES_TO_LINT=$(git diff --name-only --cached | tr "\n" ",")
else
    echo "Just linting"
    APPLY_FIXES=none
fi

# Do not run as root, so that "fix mode" doesn't change ownership to root ...
# https://github.com/oxsecurity/megalinter/issues/1975#issuecomment-1375511376
USER=$(id -g $UID)
if [[ $(uname -s | grep "Darwin") && ($(docker info -f "{{ .Name }}") == "docker-desktop") ]]; then
    # ... except on Docker Desktop for Mac, which takes care of permissions by itself
    # and does not support mounting a volume as a rootless user
    USER=0
fi
docker run --rm -u $USER -e APPLY_FIXES=$APPLY_FIXES -e MEGALINTER_FILES_TO_LINT="$MEGALINTER_FILES_TO_LINT" -v "$PWD":/tmp/lint oxsecurity/megalinter-cupcake:v6
