#!/bin/bash

USAGE_ARG_LIST="[OPTION]"
USAGE="Run tests".

source ./scripts/_sourced
check_for_help_flag "$@"

function lint() {
    ./scripts/lint
}

function test_app() {
    ./scripts/yarn test --watchAll=false --passWithNoTests
}

if [[ -n "${CI}" ]]; then
    if [ "$(whoami)" == "runner" ]; then
        echo "We are on GitHub, so don't run lint manually"
    else
        echo "Running locally because we don't think we are on GitHub"
        lint
    fi
    test_app
else
    lint
    test_app
fi
