#!/bin/bash

USAGE="Build container images."

source ./scripts/_sourced
check_for_help_flag "$@"

# Ensure container images are current
docker compose build

# Update Yarn dependencies
./scripts/yarn install --frozen-lockfile

# Fetch data if it doesn't exist
./scripts/fetch-data

# Build static asset bundle for React frontend
./scripts/yarn run build
